# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-05-22 03:19
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todomodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2018, 5, 22))),
                ('description', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Done'), ('3', 'Not Required')], default='Pending', max_length=10)),
                ('employee_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
