# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-03-28 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todomodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('description', models.TextField(max_length=500)),
                ('pending', models.IntegerField()),
                ('done', models.IntegerField()),
            ],
        ),
    ]
