# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-04-20 08:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todomodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_num', models.IntegerField(default='')),
                ('date', models.DateField(default=datetime.date(2018, 4, 20))),
                ('description', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('1', 'Pending'), ('2', 'Done'), ('3', 'Not Required')], default='Pending', max_length=10)),
            ],
        ),
    ]
