# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-04-23 09:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='date',
            field=models.DateField(default=datetime.date(2018, 4, 23)),
        ),
    ]
