# Generated by Django 2.0.3 on 2018-10-24 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='date',
            field=models.DateField(default=datetime.date(2018, 10, 24)),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Done'), ('3', 'Not Required'), ('4', 'Delete')], default='Pending', max_length=10),
        ),
    ]
