# Generated by Django 2.0.3 on 2018-10-25 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todoapp', '0002_auto_20181024_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='date',
            field=models.DateField(default=datetime.date(2018, 10, 25)),
        ),
    ]
