# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-05-02 02:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todoapp', '0002_auto_20180423_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='date',
            field=models.DateField(default=datetime.date(2018, 5, 2)),
        ),
    ]
