# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-05-06 08:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todoapp', '0003_auto_20180502_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='date',
            field=models.DateField(default=datetime.date(2018, 5, 6)),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='employee_num',
            field=models.IntegerField(blank=True),
        ),
    ]
