# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-04-11 13:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Todoapp', '0003_auto_20180402_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='done',
        ),
        migrations.RemoveField(
            model_name='todomodel',
            name='pending',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='status',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second')], default=datetime.datetime(2018, 4, 11, 13, 54, 11, 237000, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='date',
            field=models.DateField(default=datetime.date(2018, 4, 11)),
        ),
    ]
