# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-04-11 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todoapp', '0004_auto_20180411_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Done')], default='Pending', max_length=10),
        ),
    ]
