# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-05-06 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todoapp', '0004_auto_20180506_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='employee_num',
            field=models.IntegerField(default=1),
        ),
    ]
